version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: zay_dev
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mariadb

  cl-exam-backend:
    # image:  zimage-backend
    image: hana2023/zimage-backend
    restart: always
    ports:
      - 3000:3000
#    command: npm run db:migrate --y && npm run db:seed --y
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: root
      DB_DATABASE: zay_dev
      DB_PASSWORD: root
    depends_on: 
      -  db

  cl-exam-frontend:
    # image:  zimage-frontend
    image: hana2023/zimage-frontend
    restart: always
    ports:
      - 8000:8000

volumes:
  db: